### PR TITLE
Fix integration test

### LINKED ISSUE #21: ros2_control integration test is flaky
**Describe the bug**
```
2025-08-04T04:18:22.6167268Z     Start 2: test_ros2_control.test.py
2025-08-04T04:18:22.6167436Z 
2025-08-04T04:18:22.6171304Z 2: Test command: /usr/bin/python3 "-u" "/opt/ros/kilted/share/ament_cmake_test/cmake/run_test.py" "/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface/test_results/joint_state_topic_hardware_interface/test_ros2_control.test.py.xunit.xml" "--package-name" "joint_state_topic_hardware_interface" "--output-file" "/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface/ros_test/test_ros2_control.test.py.txt" "--command" "ros2" "test" "/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/ros2_control.test.py" "test_file:=/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/test_topic_based_robot.py" "--junit-xml=/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface/test_results/joint_state_topic_hardware_interface/test_ros2_control.test.py.xunit.xml" "--package-name=joint_state_topic_hardware_interface"
2025-08-04T04:18:22.6175536Z 2: Working Directory: /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface
2025-08-04T04:18:22.6176242Z 2: Test timeout computed to be: 120
2025-08-04T04:18:22.6176821Z 2: -- run_test.py: invoking following command in '/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface':
2025-08-04T04:18:22.6179444Z 2:  - ros2 test /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/ros2_control.test.py test_file:=/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/test_topic_based_robot.py --junit-xml=/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/joint_state_topic_hardware_interface/test_results/joint_state_topic_hardware_interface/test_ros2_control.test.py.xunit.xml --package-name=joint_state_topic_hardware_interface
2025-08-04T04:18:22.6181542Z 2: Running with ROS_DOMAIN_ID 1
2025-08-04T04:18:22.6181763Z 2: ROS_DOMAIN_ID 1
2025-08-04T04:18:22.6182130Z 2: [INFO] [launch]: All log files can be found below /root/.ros/log/2025-08-04-04-16-23-003602-bb162a537e15-49385
2025-08-04T04:18:22.6182592Z 2: [INFO] [launch]: Default logging verbosity is set to INFO
2025-08-04T04:18:22.6183748Z 2: test_run_complete (joint_state_topic_hardware_interface.TestWaitForCompletion.test_run_complete) ... Warning: Automatically adding attributes like self.proc_info to the test class will be deprecated in a future release.  Instead, add proc_info to the test method argument list to access the test object you need
2025-08-04T04:18:22.6184858Z 2: [INFO] [robot_state_publisher-1]: process started with pid [49389]
2025-08-04T04:18:22.6185235Z 2: [INFO] [ros2_control_node-2]: process started with pid [49390]
2025-08-04T04:18:22.6185572Z 2: [INFO] [spawner-3]: process started with pid [49391]
2025-08-04T04:18:22.6185878Z 2: [INFO] [spawner-4]: process started with pid [49392]
2025-08-04T04:18:22.6186178Z 2: [INFO] [python3-5]: process started with pid [49393]
2025-08-04T04:18:22.6186748Z 2: [ros2_control_node-2] [INFO] [1754280983.162324940] [controller_manager]: Using Steady (Monotonic) clock for triggering controller manager cycles.
2025-08-04T04:18:22.6187429Z 2: [robot_state_publisher-1] [INFO] [1754280983.166135222] [robot_state_publisher]: Robot initialized
2025-08-04T04:18:22.6188092Z 2: [ros2_control_node-2] [INFO] [1754280983.172164492] [controller_manager]: Subscribing to '/robot_description' topic for robot description.
2025-08-04T04:18:22.6188910Z 2: [ros2_control_node-2] [INFO] [1754280983.174516077] [controller_manager]: Enforcing command limits is enabled...
2025-08-04T04:18:22.6189581Z 2: [ros2_control_node-2] [INFO] [1754280983.194669795] [controller_manager]: update rate is 50 Hz
2025-08-04T04:18:22.6190239Z 2: [ros2_control_node-2] [INFO] [1754280983.194710531] [controller_manager]: Spawning controller_manager RT thread with scheduler priority: 50
2025-08-04T04:18:22.6191560Z 2: [ros2_control_node-2] [WARN] [1754280983.194804232] [controller_manager]: Could not enable FIFO RT scheduling policy: with error number <1>(Operation not permitted). See [https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html] for details on how to enable realtime scheduling.
2025-08-04T04:18:22.6192924Z 2: [spawner-4] [INFO] [1754280983.378672136] [spawner_joint_trajectory_controller]: waiting for service /controller_manager/list_controllers to become available...
2025-08-04T04:18:22.6193703Z 2: [ros2_control_node-2] [INFO] [1754280983.431959647] [controller_manager]: Received robot description from topic.
2025-08-04T04:18:22.6194507Z 2: [ros2_control_node-2] [INFO] [1754280983.435913165] [controller_manager]: Using JointLimiter for joint 'joint_3' in hardware 'name' : '  has position limits: true [-3.14159, 3.14159]
2025-08-04T04:18:22.6195261Z 2: [ros2_control_node-2]   has velocity limits: true [1]
2025-08-04T04:18:22.6195602Z 2: [ros2_control_node-2]   has acceleration limits: false [nan]
2025-08-04T04:18:22.6196021Z 2: [ros2_control_node-2]   has deceleration limits: false [nan]
2025-08-04T04:18:22.6196342Z 2: [ros2_control_node-2]   has jerk limits: false [nan]
2025-08-04T04:18:22.6196649Z 2: [ros2_control_node-2]   has effort limits: true [100]
2025-08-04T04:18:22.6196956Z 2: [ros2_control_node-2]   angle wraparound: false'
2025-08-04T04:18:22.6197524Z 2: [ros2_control_node-2] [INFO] [1754280983.435946337] [controller_manager]: Creating JointSaturationLimiter for joint 'joint_3' in hardware 'name'
2025-08-04T04:18:22.6198753Z 2: [ros2_control_node-2] [INFO] [1754280983.436245230] [controller_manager]: Using JointLimiter for joint 'joint_2' in hardware 'name' : '  has position limits: true [-3.14159, 3.14159]
2025-08-04T04:18:22.6199421Z 2: [ros2_control_node-2]   has velocity limits: true [1]
2025-08-04T04:18:22.6199844Z 2: [ros2_control_node-2]   has acceleration limits: false [nan]
2025-08-04T04:18:22.6200197Z 2: [ros2_control_node-2]   has deceleration limits: false [nan]
2025-08-04T04:18:22.6200524Z 2: [ros2_control_node-2]   has jerk limits: false [nan]
2025-08-04T04:18:22.6200826Z 2: [ros2_control_node-2]   has effort limits: true [100]
2025-08-04T04:18:22.6201124Z 2: [ros2_control_node-2]   angle wraparound: false'
2025-08-04T04:18:22.6201738Z 2: [ros2_control_node-2] [INFO] [1754280983.436268593] [controller_manager]: Creating JointSaturationLimiter for joint 'joint_2' in hardware 'name'
2025-08-04T04:18:22.6202642Z 2: [ros2_control_node-2] [INFO] [1754280983.436337523] [controller_manager]: Using JointLimiter for joint 'joint_1' in hardware 'name' : '  has position limits: true [-3.14159, 3.14159]
2025-08-04T04:18:22.6203285Z 2: [ros2_control_node-2]   has velocity limits: true [1]
2025-08-04T04:18:22.6203611Z 2: [ros2_control_node-2]   has acceleration limits: false [nan]
2025-08-04T04:18:22.6203953Z 2: [ros2_control_node-2]   has deceleration limits: false [nan]
2025-08-04T04:18:22.6204275Z 2: [ros2_control_node-2]   has jerk limits: false [nan]
2025-08-04T04:18:22.6204573Z 2: [ros2_control_node-2]   has effort limits: true [100]
2025-08-04T04:18:22.6204862Z 2: [ros2_control_node-2]   angle wraparound: false'
2025-08-04T04:18:22.6205419Z 2: [ros2_control_node-2] [INFO] [1754280983.436357430] [controller_manager]: Creating JointSaturationLimiter for joint 'joint_1' in hardware 'name'
2025-08-04T04:18:22.6206101Z 2: [ros2_control_node-2] [INFO] [1754280983.438433136] [controller_manager]: Loading hardware 'name' 
2025-08-04T04:18:22.6206855Z 2: [ros2_control_node-2] [INFO] [1754280983.441179132] [controller_manager]: Loaded hardware 'name' from plugin 'joint_state_topic_hardware_interface/JointStateTopicSystem'
2025-08-04T04:18:22.6207606Z 2: [ros2_control_node-2] [INFO] [1754280983.441546794] [controller_manager]: Initialize hardware 'name' 
2025-08-04T04:18:22.6208430Z 2: [ros2_control_node-2] [INFO] [1754280983.449262630] [controller_manager]: Successful initialization of hardware 'name'
2025-08-04T04:18:22.6209056Z 2: [ros2_control_node-2] [INFO] [1754280983.450150140] [resource_manager]: 'configure' hardware 'name' 
2025-08-04T04:18:22.6209643Z 2: [ros2_control_node-2] [INFO] [1754280983.450175017] [resource_manager]: Successful 'configure' of hardware 'name'
2025-08-04T04:18:22.6210210Z 2: [ros2_control_node-2] [INFO] [1754280983.450189814] [resource_manager]: 'activate' hardware 'name' 
2025-08-04T04:18:22.6210784Z 2: [ros2_control_node-2] [INFO] [1754280983.450206967] [resource_manager]: Successful 'activate' of hardware 'name'
2025-08-04T04:18:22.6211563Z 2: [ros2_control_node-2] [INFO] [1754280983.450392125] [controller_manager]: Resource Manager has been successfully initialized. Starting Controller Manager services...
2025-08-04T04:18:22.6212590Z 2: [ros2_control_node-2] [INFO] [1754280983.630957579] [controller_manager]: Loading controller : 'joint_trajectory_controller' of type 'joint_trajectory_controller/JointTrajectoryController'
2025-08-04T04:18:22.6213551Z 2: [ros2_control_node-2] [INFO] [1754280983.631001903] [controller_manager]: Loading controller 'joint_trajectory_controller'
2025-08-04T04:18:22.6215093Z 2: [ros2_control_node-2] [INFO] [1754280983.637484539] [controller_manager]: Controller 'joint_trajectory_controller' node arguments: --ros-args --params-file /tmp/launch_params_hkceiis8 --params-file /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/ros2_controllers.yaml 
2025-08-04T04:18:22.6216987Z 2: [spawner-4] [INFO] [1754280983.656856397] [spawner_joint_trajectory_controller]: [94mLoaded [1mjoint_trajectory_controller[0m
2025-08-04T04:18:22.6217719Z 2: [ros2_control_node-2] [INFO] [1754280983.657991871] [controller_manager]: Configuring controller: 'joint_trajectory_controller'
2025-08-04T04:18:22.6218749Z 2: [ros2_control_node-2] [INFO] [1754280983.658412332] [joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
2025-08-04T04:18:22.6219676Z 2: [ros2_control_node-2] [INFO] [1754280983.658590668] [joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
2025-08-04T04:18:22.6220472Z 2: [ros2_control_node-2] [INFO] [1754280983.658779393] [joint_trajectory_controller]: Using 'splines' interpolation method.
2025-08-04T04:18:22.6221234Z 2: [ros2_control_node-2] [INFO] [1754280983.665026228] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
2025-08-04T04:18:22.6221954Z 2: [ros2_control_node-2] [INFO] [1754280983.672378100] [joint_trajectory_controller]: Setting initial scaling factor to 1.000000
2025-08-04T04:18:22.6222762Z 2: [ros2_control_node-2] [INFO] [1754280983.672409298] [joint_trajectory_controller]: No scaling interface set. This controller will not read speed scaling from the hardware.
2025-08-04T04:18:22.6223599Z 2: [ros2_control_node-2] [INFO] [1754280983.677035073] [controller_manager]: Activating controllers: [ joint_trajectory_controller ]
2025-08-04T04:18:22.6224252Z 2: [ros2_control_node-2] [INFO] [1754280983.696097782] [controller_manager]: Successfully switched controllers!
2025-08-04T04:18:22.6225093Z 2: [spawner-4] [INFO] [1754280983.716956098] [spawner_joint_trajectory_controller]: [92mConfigured and activated [1mjoint_trajectory_controller[0m
2025-08-04T04:18:22.6225956Z 2: [spawner-3] [INFO] [1754280983.829746047] [spawner_joint_state_broadcaster]: waiting for service /controller_manager/list_controllers to become available...
2025-08-04T04:18:22.6226576Z 2: [INFO] [spawner-4]: process has finished cleanly [pid 49392]
2025-08-04T04:18:22.6227253Z 2: [ros2_control_node-2] [INFO] [1754280984.082245123] [controller_manager]: Loading controller : 'joint_state_broadcaster' of type 'joint_state_broadcaster/JointStateBroadcaster'
2025-08-04T04:18:22.6228078Z 2: [ros2_control_node-2] [INFO] [1754280984.082295728] [controller_manager]: Loading controller 'joint_state_broadcaster'
2025-08-04T04:18:22.6229639Z 2: [ros2_control_node-2] [INFO] [1754280984.084787616] [controller_manager]: Controller 'joint_state_broadcaster' node arguments: --ros-args --params-file /tmp/launch_params_hkceiis8 --params-file /home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/src/ros-controls/topic_based_hardware_interfaces/joint_state_topic_hardware_interface/test/ros2_controllers.yaml 
2025-08-04T04:18:22.6231192Z 2: [spawner-3] [INFO] [1754280984.096584601] [spawner_joint_state_broadcaster]: [94mLoaded [1mjoint_state_broadcaster[0m
2025-08-04T04:18:22.6231865Z 2: [ros2_control_node-2] [INFO] [1754280984.097593112] [controller_manager]: Configuring controller: 'joint_state_broadcaster'
2025-08-04T04:18:22.6232683Z 2: [ros2_control_node-2] [INFO] [1754280984.097684474] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
2025-08-04T04:18:22.6233577Z 2: [ros2_control_node-2] [INFO] [1754280984.116667310] [controller_manager]: Activating controllers: [ joint_state_broadcaster ]
2025-08-04T04:18:22.6234214Z 2: [ros2_control_node-2] [INFO] [1754280984.136302890] [controller_manager]: Successfully switched controllers!
2025-08-04T04:18:22.6235049Z 2: [spawner-3] [INFO] [1754280984.156756062] [spawner_joint_state_broadcaster]: [92mConfigured and activated [1mjoint_state_broadcaster[0m
2025-08-04T04:18:22.6235612Z 2: [INFO] [spawner-3]: process has finished cleanly [pid 49391]
2025-08-04T04:18:22.6236001Z 2: [INFO] [test_topic_based_robot.py-6]: process started with pid [49470]
2025-08-04T04:18:22.6236596Z 2: [test_topic_based_robot.py-6] [WARN] [1754280987.403181535] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6237355Z 2: [test_topic_based_robot.py-6] [WARN] [1754280989.403188505] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6238386Z 2: [test_topic_based_robot.py-6] [WARN] [1754280991.403664961] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6239236Z 2: [test_topic_based_robot.py-6] [WARN] [1754280993.404141668] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6239995Z 2: [test_topic_based_robot.py-6] [WARN] [1754280995.404213301] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6240826Z 2: [test_topic_based_robot.py-6] [WARN] [1754280997.404690198] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6241594Z 2: [test_topic_based_robot.py-6] [WARN] [1754280999.404879125] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6242362Z 2: [test_topic_based_robot.py-6] [WARN] [1754281001.405295196] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6243122Z 2: [test_topic_based_robot.py-6] [WARN] [1754281003.405380917] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6243872Z 2: [test_topic_based_robot.py-6] [WARN] [1754281005.405768779] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6244633Z 2: [test_topic_based_robot.py-6] [WARN] [1754281007.405798967] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6245429Z 2: [test_topic_based_robot.py-6] [WARN] [1754281009.406028000] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6246187Z 2: [test_topic_based_robot.py-6] [WARN] [1754281011.406458111] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6246945Z 2: [test_topic_based_robot.py-6] [WARN] [1754281013.406800887] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6247701Z 2: [test_topic_based_robot.py-6] [WARN] [1754281015.407109989] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6248655Z 2: [test_topic_based_robot.py-6] [WARN] [1754281017.407577009] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6249425Z 2: [test_topic_based_robot.py-6] [WARN] [1754281019.407773941] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6250201Z 2: [test_topic_based_robot.py-6] [WARN] [1754281021.407889280] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6250950Z 2: [test_topic_based_robot.py-6] [WARN] [1754281023.407945264] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6251711Z 2: [test_topic_based_robot.py-6] [WARN] [1754281025.408067456] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6252547Z 2: [test_topic_based_robot.py-6] [WARN] [1754281027.408076004] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6253404Z 2: [test_topic_based_robot.py-6] [WARN] [1754281029.408450900] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6254157Z 2: [test_topic_based_robot.py-6] [WARN] [1754281031.408832729] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6254912Z 2: [test_topic_based_robot.py-6] [WARN] [1754281033.409231239] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6255666Z 2: [test_topic_based_robot.py-6] [WARN] [1754281035.409382541] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6256478Z 2: [test_topic_based_robot.py-6] [WARN] [1754281037.409514582] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6257240Z 2: [test_topic_based_robot.py-6] [WARN] [1754281039.409656944] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6257992Z 2: [test_topic_based_robot.py-6] [WARN] [1754281041.410123695] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6258937Z 2: [test_topic_based_robot.py-6] [WARN] [1754281043.410270867] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6259710Z 2: [test_topic_based_robot.py-6] [WARN] [1754281045.410445973] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6260468Z 2: [test_topic_based_robot.py-6] [WARN] [1754281047.410755563] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6261226Z 2: [test_topic_based_robot.py-6] [WARN] [1754281049.410840328] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6261992Z 2: [test_topic_based_robot.py-6] [WARN] [1754281051.411126334] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6262753Z 2: [test_topic_based_robot.py-6] [WARN] [1754281053.411554172] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6263511Z 2: [test_topic_based_robot.py-6] [WARN] [1754281055.411962683] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6264265Z 2: [test_topic_based_robot.py-6] [WARN] [1754281057.412061341] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6265021Z 2: [test_topic_based_robot.py-6] [WARN] [1754281059.412532953] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6265784Z 2: [test_topic_based_robot.py-6] [WARN] [1754281061.412991168] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6266542Z 2: [test_topic_based_robot.py-6] [WARN] [1754281063.413343160] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:22.6267300Z 2: [test_topic_based_robot.py-6] [WARN] [1754281065.413883617] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2531836Z 2: [test_topic_based_robot.py-6] [WARN] [1754281067.414379117] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2538019Z 2: [test_topic_based_robot.py-6] [WARN] [1754281069.414737944] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2539236Z 2: [test_topic_based_robot.py-6] [WARN] [1754281071.414776478] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2540341Z 2: [test_topic_based_robot.py-6] [WARN] [1754281073.415065152] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2541258Z 2: [test_topic_based_robot.py-6] [WARN] [1754281075.415395764] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2542226Z 2: [test_topic_based_robot.py-6] [WARN] [1754281077.415769812] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2543097Z 2: [test_topic_based_robot.py-6] [WARN] [1754281079.416176141] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2543994Z 2: [test_topic_based_robot.py-6] [WARN] [1754281081.416721551] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2544904Z 2: [test_topic_based_robot.py-6] [WARN] [1754281083.416872551] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2545859Z 2: [test_topic_based_robot.py-6] [WARN] [1754281085.417051955] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2546744Z 2: [test_topic_based_robot.py-6] [WARN] [1754281087.417495576] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2547672Z 2: [test_topic_based_robot.py-6] [WARN] [1754281089.417849547] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2548700Z 2: [test_topic_based_robot.py-6] [WARN] [1754281091.418201631] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2549575Z 2: [test_topic_based_robot.py-6] [WARN] [1754281093.418416728] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2550480Z 2: [test_topic_based_robot.py-6] [WARN] [1754281095.418773741] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2551375Z 2: [test_topic_based_robot.py-6] [WARN] [1754281097.418784954] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2552222Z 2: [test_topic_based_robot.py-6] [WARN] [1754281099.418837717] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2553076Z 2: [test_topic_based_robot.py-6] [WARN] [1754281101.419029578] [topic_based_robot]: Waiting for current joint states from topic '/joint_states'...
2025-08-04T04:18:23.2553768Z 2/2 Test #2: test_ros2_control.test.py ...................***Timeout 120.00 sec
```

**To Reproduce**
https://github.com/ros-controls/ros2_control_ci/issues/434

**Environment (please complete the following information):**
 - OS: Noble
 - Version kilted

### PR DESCRIPTION
**Pull request by christophfroehlich**
I rewrote the tests using the idea from https://docs.ros.org/en/rolling/Tutorials/Intermediate/Testing/Integration.html

## First idea:
This all did not help, but adding a timer re-sending the actual_joint_states did the job.

Fixes #21 #22  #23

[2a6f1a8](https://github.com/ros-controls/topic_based_hardware_interfaces/pull/42/commits/2a6f1a886b04cdaf672c49612970a29935756337) fixes also #10 

Then I realized that we don't even test if commands are received

## Current idea:

- use topic_tools relay executable instead of custom python robot node, and mirror commands to states
- Adapt the example_position executable from gz_ros2_control_demos to test if the commands from the controllers are processed correctly

### CODE REVIEW

File: joint_state_topic_hardware_interface/test/example_position.cpp [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+{
+  std::cout << "feedback->desired: positions: " << feedback->desired.positions.at(0);
+  std::cout << ", velocities: " << feedback->desired.velocities.at(0) << std::endl;
+
+  std::cout << "feedback->actual: positions: " << feedback->actual.positions.at(0);
+  std::cout << std::endl;
+
+  if (ct_goals_reached < desired_goals.size())
+  {
+    if (fabs(feedback->actual.positions[0] - desired_goals.at(ct_goals_reached)) < 0.1)
```
Comment (MarqRazz) [inline joint_state_topic_hardware_interface/test/example_position.cpp]: This seems like a large tolerance for mock_hardware. Does it need to be this big?

**Review by MarqRazz — APPROVED** [review]
Thanks for fixing the test @christophfroehlich! Few small comments but otherwise looks good.

**Review by JafarAbdi — APPROVED** [review]
lgtm

Sorry haven't had time to look into PRs, life is busy 🫠. Hopefully will be better soon
